/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppMyIssuesRouteImport } from './routes/app/my-issues'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProjectKeyRouteImport } from './routes/app/project/$key'
import { Route as AppProjectKeyBoardRouteImport } from './routes/app/project/$key/board'
import { Route as AppProjectKeyListRouteImport } from './routes/app/project/$key/list'
import { Route as AppProjectKeyIssueIssueKeyRouteImport } from './routes/app/project/$key/issue/$issueKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppMyIssuesRoute = AppMyIssuesRouteImport.update({
  id: '/my-issues',
  path: '/my-issues',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectKeyRoute = AppProjectKeyRouteImport.update({
  id: '/project/$key',
  path: '/project/$key',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectKeyBoardRoute = AppProjectKeyBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppProjectKeyRoute,
} as any)
const AppProjectKeyListRoute = AppProjectKeyListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AppProjectKeyRoute,
} as any)
const AppProjectKeyIssueIssueKeyRoute =
  AppProjectKeyIssueIssueKeyRouteImport.update({
    id: '/issue/$issueKey',
    path: '/issue/$issueKey',
    getParentRoute: () => AppProjectKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/home': typeof AppHomeRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/my-issues': typeof AppMyIssuesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/project/$key': typeof AppProjectKeyRouteWithChildren
  '/app/project/$key/board': typeof AppProjectKeyBoardRoute
  '/app/project/$key/list': typeof AppProjectKeyListRoute
  '/app/project/$key/issue/$issueKey': typeof AppProjectKeyIssueIssueKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/home': typeof AppHomeRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/my-issues': typeof AppMyIssuesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/project/$key': typeof AppProjectKeyRouteWithChildren
  '/app/project/$key/board': typeof AppProjectKeyBoardRoute
  '/app/project/$key/list': typeof AppProjectKeyListRoute
  '/app/project/$key/issue/$issueKey': typeof AppProjectKeyIssueIssueKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/home': typeof AppHomeRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/my-issues': typeof AppMyIssuesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/project/$key': typeof AppProjectKeyRouteWithChildren
  '/app/project/$key/board': typeof AppProjectKeyBoardRoute
  '/app/project/$key/list': typeof AppProjectKeyListRoute
  '/app/project/$key/issue/$issueKey': typeof AppProjectKeyIssueIssueKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/home'
    | '/app/inbox'
    | '/app/my-issues'
    | '/app/settings'
    | '/app/'
    | '/app/project/$key'
    | '/app/project/$key/board'
    | '/app/project/$key/list'
    | '/app/project/$key/issue/$issueKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/home'
    | '/app/inbox'
    | '/app/my-issues'
    | '/app/settings'
    | '/app'
    | '/app/project/$key'
    | '/app/project/$key/board'
    | '/app/project/$key/list'
    | '/app/project/$key/issue/$issueKey'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/home'
    | '/app/inbox'
    | '/app/my-issues'
    | '/app/settings'
    | '/app/'
    | '/app/project/$key'
    | '/app/project/$key/board'
    | '/app/project/$key/list'
    | '/app/project/$key/issue/$issueKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-issues': {
      id: '/app/my-issues'
      path: '/my-issues'
      fullPath: '/app/my-issues'
      preLoaderRoute: typeof AppMyIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/project/$key': {
      id: '/app/project/$key'
      path: '/project/$key'
      fullPath: '/app/project/$key'
      preLoaderRoute: typeof AppProjectKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/project/$key/board': {
      id: '/app/project/$key/board'
      path: '/board'
      fullPath: '/app/project/$key/board'
      preLoaderRoute: typeof AppProjectKeyBoardRouteImport
      parentRoute: typeof AppProjectKeyRoute
    }
    '/app/project/$key/list': {
      id: '/app/project/$key/list'
      path: '/list'
      fullPath: '/app/project/$key/list'
      preLoaderRoute: typeof AppProjectKeyListRouteImport
      parentRoute: typeof AppProjectKeyRoute
    }
    '/app/project/$key/issue/$issueKey': {
      id: '/app/project/$key/issue/$issueKey'
      path: '/issue/$issueKey'
      fullPath: '/app/project/$key/issue/$issueKey'
      preLoaderRoute: typeof AppProjectKeyIssueIssueKeyRouteImport
      parentRoute: typeof AppProjectKeyRoute
    }
  }
}

interface AppProjectKeyRouteChildren {
  AppProjectKeyBoardRoute: typeof AppProjectKeyBoardRoute
  AppProjectKeyListRoute: typeof AppProjectKeyListRoute
  AppProjectKeyIssueIssueKeyRoute: typeof AppProjectKeyIssueIssueKeyRoute
}

const AppProjectKeyRouteChildren: AppProjectKeyRouteChildren = {
  AppProjectKeyBoardRoute: AppProjectKeyBoardRoute,
  AppProjectKeyListRoute: AppProjectKeyListRoute,
  AppProjectKeyIssueIssueKeyRoute: AppProjectKeyIssueIssueKeyRoute,
}

const AppProjectKeyRouteWithChildren = AppProjectKeyRoute._addFileChildren(
  AppProjectKeyRouteChildren,
)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMyIssuesRoute: typeof AppMyIssuesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectKeyRoute: typeof AppProjectKeyRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppInboxRoute: AppInboxRoute,
  AppMyIssuesRoute: AppMyIssuesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectKeyRoute: AppProjectKeyRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
